const str={type:'string'},num={type:'integer'},strings={type:'array',items:str},ids={type:'array',items:num};
const tool=(name:string,description:string,properties:Record<string,unknown>,required:string[]= ['identity'])=>({name,description,inputSchema:{type:'object',properties:{identity:str,...properties},required}});
export const COGNITION_TOOLS=[
 tool('mind_focus','Session working memory. Open/read, then update/park/resume/close with expected_revision. Keep decisions, assumptions, sources and next steps in document; replacements are explicit. Separate session keys prevent cross-session overwrites.',{action:{enum:['open','read','list','history','update','park','resume','close'],type:'string'},session_key:str,expected_revision:num,document:{type:'object',additionalProperties:true},retention_days:num,limit:num}),
 tool('mind_context','Bounded source-backed recall for a wake, resume, topic change or action. Returns independent identity, relationships, inner-life, experience, intentions, procedures and working-memory sections, freshness, omissions and a feedback receipt. No memory content is rewritten.',{query:str,session_key:str,max_chars:num}),
 tool('mind_evidence','Read/annotate/verify a memory with sources, epistemic kind, event time, validity and contradictions. expected_revision is 0 for first annotation. Corrections flag dependent claims for review without overwriting them.',{action:{type:'string',enum:['read','annotate','verify']},observation_id:num,expected_revision:num,epistemic_kind:{type:'string',enum:['unclassified','event','report','interpretation','hypothesis','imagining']},event_at:str,valid_until:str,applicability:str,source_ids:ids,contradicts:ids,reason:str},['identity','observation_id']),
 tool('mind_scope','Define, read or revise the conditions under which an existing memory is true. Scope revisions preserve prior scope and flag dependent conclusions for review without changing the memory statement.',{action:{type:'string',enum:['read','define','revise']},observation_id:num,expected_revision:num,applies_when:strings,does_not_apply_when:strings,source_ids:ids,reason:str},['identity','observation_id']),
 tool('mind_recall_feedback','Give useful/irrelevant/outdated/missing feedback on an actual mind_context receipt, or retract by feedback_id. Missing requires an observation reference. Ranking effects are bounded and reversible; feedback cannot rewrite truth.',{action:{type:'string',enum:['record','retract']},receipt_id:str,source_ref:str,judgment:{type:'string',enum:['useful','irrelevant','outdated','missing']},reason:str,feedback_id:str}),
 tool('mind_procedure','General deliberate practice using the Sketchbook evidence and revision engine. Study a code/tool/writing artifact, record scoped steps and failure modes, set one practice, apply, then review using a later evidence_study_id. Conclusive evidence must be independent; source_path should identify an immutable artifact or use evidence_observation_id. Read and recall return current guidance and revision history.',{action:{type:'string',enum:['study','compare','practice','apply','review','read','recall','list']},domain:str,title:str,study_id:num,lesson_id:num,experiment_id:num,evidence_observation_id:num,evidence_study_id:num,compare_to_study_id:num,source_path:str,summary:str,applicability:str,prerequisites:strings,steps:strings,failure_modes:strings,tool_version:str,tools_used:{type:'array',items:{type:'object',properties:{tool:str,operation:str,effect:str,keep:str,change:str}}},lessons:{type:'array',items:{type:'object',properties:{category:str,tool_name:str,principle:str,observed_effect:str}}},next_experiment:str,hypothesis:str,plan:str,target_title:str,focus:str,result:str,verdict:{type:'string',enum:['confirmed','revised','rejected','inconclusive']},revised_principle:str,query:str,tool_names:strings,tags:strings,limit:num}),
];
